source "http://rubygems.org"

gem 'rake'
gem 'rack'
gem 'jekyll', '~> 2.0'
gem 'jekyll-sitemap'
gem 'jekyll-page-hooks'
gem 'octopress-codefence', '~> 1.4'
gem 'octopress-codeblock', '~> 1.0'
gem 'octopress-gist', '~> 1.2'
gem 'liquid', '2.5.5'
gem 'redcarpet'
gem 'compass'
gem 'rubypants'
gem 'stringex'
gem 'sinatra'
gem 'thin'
gem 'maruku', '0.7.0'
gem 'rouge'
