source "http://rubygems.org"

gem 'rake'
gem 'rack'
gem 'jekyll', '~> 2.0'
gem 'jekyll-sitemap'
gem 'octopress-hooks'
gem 'octopress-codefence', '~> 1.4'
gem 'octopress-codeblock', '~> 1.0'
gem 'octopress-gist', '~> 1.3'
gem 'octopress-render-code', '~> 1.0'
gem 'octopress-render-tag', '~> 1.0'
gem 'liquid', '2.5.5'
gem 'redcarpet'
gem 'compass', '~> 0.12'
gem 'sass-globbing', '~> 1.0'
gem 'rubypants', '~> 0.2'
gem 'stringex', '~> 1.4'
gem 'sinatra'
gem 'thin', '~> 1.7'
gem 'maruku', '0.7.0'
gem 'rouge'
