source "http://rubygems.org"

gem 'rake'
gem 'rack'
gem 'jekyll', '~> 2.0'
gem 'jekyll-sitemap'
gem 'jekyll-page-hooks'
gem 'octopress-codefence'
gem 'octopress-gist'
gem 'liquid', '2.5.5'
gem 'redcarpet'
gem 'compass'
gem 'rubypants'
gem 'stringex'
gem 'sinatra'
gem 'thin'
gem 'maruku', '0.7.0'
gem 'rouge'
